### ISSUE TITLE
[MeetUp] Café Virtual | Sáb, 30.07.2022 | de 20h às 21h | horário de brasília 

### ISSUE THREAD

**Issue by bpires** [ti-no-canada/imigracao-para-o-canada#36]
![1](https://user-images.githubusercontent.com/86871991/179844805-c29f64bd-ccfa-4583-aec5-60ab0c601b2b.png)

# Café Virtual | Ti no Canadá

Sobre o evento:
- Online (Google Meet)
- Língua: Português
- Formato: _coffee chat_ (informal)
- Pauta livre / integração entre os membros

> Vamos aproveitar o momento para discutir a viabilidade de realizar MeetUp's de forma recorrente ou eventos de interesse dos membros do grupo.

---
- Data: **Sábado, 30.07.2022**
- Duração: **1 (uma) hora**
- Horário: **entre 16h e 21h (horário de brasília)**\*

> \* O horário está sendo definido por meio de [enquete no grupo do Telegram](https://t.me/tinocanada/126027).
> Não deixe de votar, após o encerramento da votação será atualizado.

**Comment by bpires** [comment]
## O horário escolhido foi **20pm-21pm,** com 15 votos.

Em segundo lugar, ficou o horário de 16pm-17pm, com 13 votos. Na próxima edição, tentamos fazer mais cedo para contemplar outras pessoas

![image](https://user-images.githubusercontent.com/86871991/180512136-bcc620f3-7978-469e-b934-379d53f3de00.png)

**Comment by MarcosCostaDev** [comment]
@bpires atualiza o título da issue com o horário escolhido.

**Comment by bpires** [comment]
### 📋 Presentes:

1	Alef Janguas da costa
2	Alexandre Alves
3	Daniel Rosa
4	Diego Coelho
5	Heyglon Fábio
6	Hugo Azevedo
7	Jonata Nassula
8	Jonathan Barreira
9	Jonathan Silva
10	Jucelio Delmondes
11	Leticia de Moura
12	Marcelo Mendes
13	Marcelo Pinheiro
14	Marina Faria
15	Julio
16	Rafael Barros
17	Thiago Eltz
18	William Severino
19	Yago Dyogennes
20		


### 📸 Registros do evento:


<img src="https://user-images.githubusercontent.com/86871991/182071795-9147e1df-8f51-4a0a-89bb-60fd0ae65d09.jpg" width="75%" height="75%" />

---

<img src="https://user-images.githubusercontent.com/86871991/182071872-af4068cc-6fc0-46b4-b386-2b1b85d3f4a3.jpg" width="75%" height="75%" />
